version: '2'
services:  
  shortest-path:
    image: node:latest
    volumes:
      - ./:/usr/src/service/
    working_dir: /usr/src/service/
    ports:
      - 80:8080
    environment:
    - NODE_ENV=dev
    command: bash -c "npm install && npm run dev-start"
  