version: '2'
services:  
  web:
    image: node:latest
    volumes:
      - ./:/usr/src/service/
    working_dir: /usr/src/service/
    ports:
      - 80:8080
    command: bash -c "npm install && npm run dev-start"
  test:
    image: node:latest
    volumes:
      - ./:/usr/src/service/
    working_dir: /usr/src/service/
    command: bash -c "npm install && npm run test"
  